### ISSUE TITLE
Backend issue

### ISSUE THREAD

**Issue by chloebourbion** [c3pm-labs/platform#29]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
When I try to sign up the API return "User already exist" while I have no user in my database

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
go on `plaform/e2e-tests` branch, in the `e2e` directory, run a docker with postgres then `npm run test:e2e:dev`
When you run the register test, you will see the error log in the API with "error: user already exist"

* **What is the expected behavior?**
user should be created and logged in

**Comment by gabrielcolson** [comment]
@chloebourbion this issue has been solved, right?

**Comment by chloebourbion** [comment]
@gabrielcolson right!
