### ISSUE TITLE
Translation and ToS disappear

### ISSUE THREAD

**Issue by chloebourbion** [c3pm-labs/platform#90]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Sometimes Language switch + ToS link disappear, I don't really know why it appened

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Sometimes Language switch + ToS link disappear, I don't really know why it happened. I clicked on "discover package" on the home page, and while it was loading I when back on the home page.

* **What is the expected behavior?**
The language switch and ToS link should always be present (on each page)

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: XX
  - Browser: [all | Chrome XX | Firefox XX | Safari XX 
    Mobile: Android X.X | iOS XX 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chloebourbion** [comment]
exemple: https://c3pm.io/search?q=&page=5

**Comment by gabrielcolson** [comment]
Can't reproduce on https://staging.c3pm.io
